nameOverride:

holmes:
  image: holmes:0.14.2-hf5
  registry: us-central1-docker.pkg.dev/genuine-flight-317411/devel
  additionalEnvVars: []

  modelList:
    bedrock-claude-sonnet-4:
      aws_access_key_id: "{{ env.AWS_ACCESS_KEY_ID }}"
      aws_secret_access_key: "{{ env.AWS_SECRET_ACCESS_KEY }}"
      aws_region_name: eu-south-2
      model: bedrock/eu.anthropic.claude-sonnet-4-20250514-v1:0
      temperature: 1
      thinking:
        budget_tokens: 10000
        type: enabled

  toolsets:
    helm/core:
      enabled: true
    git:
      enabled: true

  mcp_servers:
    konnect-mcp:
      description: "Kong Konnect MCP"
      url: "http://konnect-mcp:8003/sse"
    slack-mcp:
      description: "Slack MCP"
      url: "http://slack-mcp:8003/sse"

aiagent:
  enabled: true
  schedule: "*/5 * * * *" # Every 5 minutes
  model: "eu.anthropic.claude-sonnet-4-20250514-v1:0"
  prompt: #Override the prompt
  slack_channel_id: ""
  image:
    repository: curlimages/curl
    tag: "8.8.0"
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistrKeySecretName

mcp:
  konnect:
    env: []
    envConfigMap: ""
    envSecret: ""
    image:
      repository: thegatewayguy/superbase-konnect-mcp
      tag: "1.0.0"
      pullPolicy: IfNotPresent
      # pullSecrets:
      #   - myRegistrKeySecretName
    replicas: 1

  slack:
    version: "latest"
    env: []
    envConfigMap: ""
    envSecret: ""
    image:
      repository: supercorp/supergateway
      tag: "latest"
      pullPolicy: IfNotPresent
      # pullSecrets:
      #   - myRegistrKeySecretName
    replicas: 1