nameOverride:

holmes:
  additionalEnvVars: []

  modelList:
    claude-sonnet:
      api_key: "{{ env.ANTHROPIC_API_KEY }}"
      model: anthropic/claude-sonnet-4-20250514
      temperature: 0

  toolsets:
    helm/core:
      enabled: true
    git:
      enabled: true

  mcp_servers:
    konnect-mcp:
      description: "Kong Konnect MCP"
      url: "http://konnect-mcp:8003"
    slack-mcp:
      description: "Slack MCP"
      url: "http://slack-mcp:8003"

aiagent:
  enabled: true
  schedule: "*/5 * * * *" # Every 5 minutes
  model: "claude-sonnet-4-20250514"
  prompt: "Using Konnect Analytics which route is throwing a non 200 error in the last 5 minutes? If there are no issues
  in the last 15 minutes then send a message to Slack channel with id of C09HN7LCC6N with a summary of your findings.
  If you find a route that is causing the error check the github repository YAML configuration to locate the file that needs changing.
  Create a pull request to resolve this issue. You will be working in files that define configuration in YAML so please make sure 
  you remove all the necessary files, so if its an element in a YAML list please remove the entire element. 
  Please make sure you complete all the changes in 1 commit and not multiple. Then return the name of the control plane 
  and then name of the route. Send that information to Slack channel with id of C09HN7LCC6N and give a 
  description as to what the problem is and a link to the PR that you created and a list of all the tasks you performed to achieve this."
  image:
    repository: curlimages/curl
    tag: "8.8.0"
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistrKeySecretName

mcp:
  konnect:
    env: []
    envConfigMap: ""
    envSecret: ""
    image:
      repository: thegatewayguy/superbase-konnect-mcp
      tag: "1.0.0"
      pullPolicy: IfNotPresent
      # pullSecrets:
      #   - myRegistrKeySecretName
    replicas: 1

  slack:
    version: "latest"
    env: []
    envConfigMap: ""
    envSecret: ""
    image:
      repository: supercorp/supergateway
      tag: "latest"
      pullPolicy: IfNotPresent
      # pullSecrets:
      #   - myRegistrKeySecretName
    replicas: 1